#### Imports / setup

In [22]:
import os
import random
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics

from mlxtend.plotting import plot_confusion_matrix
from mlxtend.plotting import plot_decision_regions

from matplotlib import pyplot as plt

import tensorflow
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras import optimizers
from tensorflow.keras.utils import plot_model

print(tensorflow.__version__)

2.16.2

### Charger les données

In [23]:
df = pd.read_csv('./dataset/labels.csv')
df

                                     id                     breed
0      000bec180eb18c7604dcecc8fe0dba07               boston_bull
1      001513dfcb2ffafc82cccf4d8bbaba97                     dingo
2      001cdf01b096e06d78e9e5112d419397                  pekinese
3      00214f311d5d2247d5dfe4fe24b2303d                  bluetick
4      0021f9ceb3235effd7fcde7f7538ed62          golden_retriever
...                                 ...                       ...
10217  ffd25009d635cfd16e793503ac5edef0                    borzoi
10218  ffd3f636f7f379c51ba3648a9ff8254f            dandie_dinmont
10219  ffe2ca6c940cddfee68fa3cc6c63213f                  airedale
10220  ffe5f6d8e2bff356e9482a80a6e29aac        miniature_pinscher
10221  fff43b07992508bc822f33d8ffd902ae  chesapeake_bay_retriever

[10222 rows x 2 columns]

### Traitement de données

In [24]:
# traiter les valeurs manquantes
df = df.dropna()
# supprimer les doublons
df = df.drop_duplicates()

df

                                     id                     breed
0      000bec180eb18c7604dcecc8fe0dba07               boston_bull
1      001513dfcb2ffafc82cccf4d8bbaba97                     dingo
2      001cdf01b096e06d78e9e5112d419397                  pekinese
3      00214f311d5d2247d5dfe4fe24b2303d                  bluetick
4      0021f9ceb3235effd7fcde7f7538ed62          golden_retriever
...                                 ...                       ...
10217  ffd25009d635cfd16e793503ac5edef0                    borzoi
10218  ffd3f636f7f379c51ba3648a9ff8254f            dandie_dinmont
10219  ffe2ca6c940cddfee68fa3cc6c63213f                  airedale
10220  ffe5f6d8e2bff356e9482a80a6e29aac        miniature_pinscher
10221  fff43b07992508bc822f33d8ffd902ae  chesapeake_bay_retriever

[10222 rows x 2 columns]

### Création du modèle

In [35]:
# création du modèle dog_breed_model
def create_model(input_dim, output_dim):
    model = Sequential()
    model.add(Input(shape=(input_dim,)))
    model.add(Dense(128, activation='relu'))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(output_dim, activation='softmax'))
    return model
# Préparation des données
X = pd.get_dummies(df.drop(columns=['breed']), drop_first=True).astype(np.float32)
y = df['breed']
le = LabelEncoder()
y_encoded = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)
input_dim = X_train.shape[1]
output_dim = len(le.classes_)
model = create_model(input_dim, output_dim)
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_21 (Dense)                │ (None, 128)            │     1,308,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 120)            │         7,800 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,324,472 (5.05 MB)

 Trainable params: 1,324,472 (5.05 MB)

 Non-trainable params: 0 (0.00 B)

### Entraînement du modèle

In [36]:
# entrainement du modèle

history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

Epoch 1/50

2026-01-28 11:46:20.720846: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

205/205 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.0105 - loss: 4.7866 - val_accuracy: 0.0092 - val_loss: 4.7849
Epoch 2/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.0298 - loss: 4.7404 - val_accuracy: 0.0104 - val_loss: 4.7866
Epoch 3/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.2798 - loss: 4.3661 - val_accuracy: 0.0110 - val_loss: 4.8036
Epoch 4/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9317 - loss: 2.4742 - val_accuracy: 0.0104 - val_loss: 4.8818
Epoch 5/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 0.3601 - val_accuracy: 0.0110 - val_loss: 5.0660
Epoch 6/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 0.0619 - val_accuracy: 0.0067 - val_loss: 5.0933
Epoch 7/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 0.0304 - val_accuracy: 0.0073 - val_loss: 5.1169
Epoch 8/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 0.0187 - val_accuracy: 0.0092 - val_loss: 5.1370
Epoch 9/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 0.0127 - val_accuracy: 0.0079 - val_loss: 5.1567
Epoch 10/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 1.0000 - loss: 0.0092 - val_accuracy: 0.0067 - val_loss: 5.1816
Epoch 11/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 0.0070 - val_accuracy: 0.0079 - val_loss: 5.1947
Epoch 12/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.0086 - val_loss: 5.2141
Epoch 13/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.0073 - val_loss: 5.2282
Epoch 14/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.0098 - val_loss: 5.2374
Epoch 15/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.0079 - val_loss: 5.2474
Epoch 16/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.0086 - val_loss: 5.2611
Epoch 17/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.0086 - val_loss: 5.2736
Epoch 18/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.0092 - val_loss: 5.2855
Epoch 19/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.0092 - val_loss: 5.2985
Epoch 20/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.0086 - val_loss: 5.3067
Epoch 21/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.0079 - val_loss: 5.3210
Epoch 22/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 8.9972e-04 - val_accuracy: 0.0086 - val_loss: 5.3317
Epoch 23/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 7.7773e-04 - val_accuracy: 0.0079 - val_loss: 5.3412
Epoch 24/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 6.7446e-04 - val_accuracy: 0.0086 - val_loss: 5.3515
Epoch 25/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 5.8637e-04 - val_accuracy: 0.0086 - val_loss: 5.3648
Epoch 26/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 5.1148e-04 - val_accuracy: 0.0079 - val_loss: 5.3752
Epoch 27/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 4.4678e-04 - val_accuracy: 0.0073 - val_loss: 5.3870
Epoch 28/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 3.9124e-04 - val_accuracy: 0.0073 - val_loss: 5.3942
Epoch 29/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 3.4301e-04 - val_accuracy: 0.0067 - val_loss: 5.4071
Epoch 30/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 3.0126e-04 - val_accuracy: 0.0067 - val_loss: 5.4181
Epoch 31/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 2.6502e-04 - val_accuracy: 0.0061 - val_loss: 5.4268
Epoch 32/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 2.3334e-04 - val_accuracy: 0.0079 - val_loss: 5.4337
Epoch 33/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 2.0582e-04 - val_accuracy: 0.0067 - val_loss: 5.4488
Epoch 34/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 1.8164e-04 - val_accuracy: 0.0067 - val_loss: 5.4594
Epoch 35/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 1.6044e-04 - val_accuracy: 0.0049 - val_loss: 5.4704
Epoch 36/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 1.4187e-04 - val_accuracy: 0.0061 - val_loss: 5.4793
Epoch 37/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 1.2556e-04 - val_accuracy: 0.0061 - val_loss: 5.4896
Epoch 38/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 1.1118e-04 - val_accuracy: 0.0061 - val_loss: 5.5009
Epoch 39/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 9.8522e-05 - val_accuracy: 0.0055 - val_loss: 5.5117
Epoch 40/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 8.7362e-05 - val_accuracy: 0.0061 - val_loss: 5.5220
Epoch 41/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 7.7507e-05 - val_accuracy: 0.0055 - val_loss: 5.5341
Epoch 42/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 6.8804e-05 - val_accuracy: 0.0049 - val_loss: 5.5444
Epoch 43/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 6.1098e-05 - val_accuracy: 0.0049 - val_loss: 5.5557
Epoch 44/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 5.4270e-05 - val_accuracy: 0.0055 - val_loss: 5.5677
Epoch 45/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 4.8242e-05 - val_accuracy: 0.0043 - val_loss: 5.5740
Epoch 46/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 4.2895e-05 - val_accuracy: 0.0043 - val_loss: 5.5879
Epoch 47/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 3.8147e-05 - val_accuracy: 0.0043 - val_loss: 5.5979
Epoch 48/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 3.3952e-05 - val_accuracy: 0.0049 - val_loss: 5.6100
Epoch 49/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 1.0000 - loss: 3.0222e-05 - val_accuracy: 0.0043 - val_loss: 5.6186
Epoch 50/50
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 2.6914e-05 - val_accuracy: 0.0043 - val_loss: 5.6320

### Tests du modèle

In [39]:
# évaluation du modèle
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')
# Prédictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Enregistrement des résultats dans un fichier .h5
model.save('dog_breed_model.h5')

64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0054 - loss: 5.6284
Test Loss: 5.62839412689209, Test Accuracy: 0.005378973204642534
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.